<?php

 $_CONFIG = array (
  'firstrun' => false,
  'admin_color_scheme' => 'blue',
  'align_logo' => 'center',
  'appname' => 'SGS Admin',
  'basedir' => '',
  'clipboard' => false,
  'default_timezone' => 'America/New_York',
  'delete_dir_enable' => true,
  'delete_enable' => true,
  'description' => '&lt;p&gt;&lt;br&gt;&lt;/p&gt;',
  'email_from' => '',
  'email_login' => '',
  'email_pass' => '',
  'enable_prettylinks' => false,
  'filedefnum' => 50,
  'filedeforder' => 'date',
  'fixed_navbar' => true,
  'folderdefnum' => 10,
  'folderdeforder' => 'alpha',
  'hidden_dirs' => 
  array (
    0 => 'vfm-admin',
  ),
  'hidden_files' => 
  array (
    0 => 'vfm-thumb.php',
    1 => 'index.php',
    2 => 'index.php~',
    3 => '.htaccess',
    4 => '.htpasswd',
    5 => '.ftpquota',
  ),
  'inline_thumbs' => false,
  'lang' => 'en',
  'lifetime' => 1000,
  'list_view' => 'list',
  'log_file' => false,
  'logo' => 'logo.png',
  'max_zip_files' => 100,
  'max_zip_filesize' => 100,
  'move_enable' => true,
  'newdir_enable' => true,
  'notify_download' => false,
  'notify_login' => false,
  'notify_newfolder' => false,
  'notify_upload' => false,
  'playmusic' => false,
  'port' => '',
  'preloader' => 'XMLHttpRequest',
  'progress_color' => '',
  'registration_enable' => false,
  'registration_role' => 'user',
  'registration_user_folders' => false,
  'registration_user_quota' => '',
  'rename_dir_enable' => true,
  'rename_enable' => true,
  'require_login' => true,
  'salt' => '7660f84ed962fb584ad586030c729697',
  'script_url' => 'https://beta.sgsadmin.com/fm/',
  'secure_conn' => 'none',
  'secure_sharing' => false,
  'selectivext' => 'reject',
  'sendfiles_enable' => true,
  'session_name' => 'vfm_499830470',
  'show_captcha' => true,
  'show_captcha_register' => false,
  'show_captcha_reset' => false,
  'show_folder_counter' => true,
  'show_head' => true,
  'show_langmenu' => false,
  'show_langname' => false,
  'show_pagination' => true,
  'show_pagination_folders' => false,
  'show_pagination_num' => true,
  'show_pagination_num_folder' => false,
  'show_path' => true,
  'show_percentage' => true,
  'show_search' => true,
  'show_usermenu' => true,
  'single_progress' => false,
  'skin' => 'vfm-2016.css',
  'smtp_auth' => false,
  'smtp_enable' => false,
  'smtp_server' => '',
  'starting_dir' => '',
  'thumbnails' => true,
  'thumbnails_height' => 800,
  'thumbnails_width' => 760,
  'time_format' => 'd/m/Y - H:i',
  'txt_direction' => 'LTR',
  'upload_allow_type' => 
  array (
  ),
  'upload_email' => false,
  'upload_enable' => true,
  'upload_notification_enable' => false,
  'upload_reject_extension' => 
  array (
    0 => 'php',
    1 => 'html',
    2 => 'htm',
    3 => 'ini',
  ),
);
